### ISSUE TITLE
training

### ISSUE THREAD

**Issue by mojganmdd** [weber0522bb/AODnet-by-pytorch#3]
Hi,

I tried to implement exact same thin you have done, I downloaded the data set of NYU called bathrooms_part1.zip and nyu_depth_v2_labeled.mat, then gave both data to the make_dataset.py and I have lots of hazy and gt images in h5 format. I chose 160 of them as training and 40 as val data and tried to train the network. the loss is around 0.005, but when I am taking the 10th epoch and test an image with it, I get yellow images!! do you have any idea what is the reason??

thanks
Mojgan

**Comment by yang165** [comment]
I also have this problem.

**Comment by Caesar-xu7** [comment]
Hello, I tried to implement your code,  when I run python create_train.py, This error occurred（Traceback (most recent call last):
  File "create_train.py", line 42, in <module>
    parser.add_argument('--dataset', type=str, require=True, help='path to  synthesized hazy images dataset store')
  File "/root/miniconda3/envs/aodnet/lib/python3.6/argparse.py", line 1338, in add_argument
    action = action_class(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'require'）
my python version is 3.6.13, pytorch = 0.4.0

**Comment by leijobs** [comment]
> Hello, I tried to implement your code, when I run python create_train.py, This error occurred（Traceback (most recent call last): File "create_train.py", line 42, in parser.add_argument('--dataset', type=str, require=True, help='path to synthesized hazy images dataset store') File "/root/miniconda3/envs/aodnet/lib/python3.6/argparse.py", line 1338, in add_argument action = action_class(**kwargs) TypeError: **init**() got an unexpected keyword argument 'require'） my python version is 3.6.13, pytorch = 0.4.0

Hello, I just found the bug, it's ‘required’ not 'require',then it works.

**Comment by NoviceQAQ** [comment]
I also downloaded the dataset nyu_depth_v2_labeled.mat and provided it to make_datasets to generate many pictures in h5 format. I selected 2400 as train data and 600 as val data. But when I select AOD_net_epoch_rule_10.pth and run test.py
AttributeError: 'collections.Orderedict' object has no attribute 'cuda', how do I solve this problem?

**Comment by oceansOfStars1** [comment]
> Hi,
> 
> I tried to implement exact same thin you have done, I downloaded the data set of NYU called bathrooms_part1.zip and nyu_depth_v2_labeled.mat, then gave both data to the make_dataset.py and I have lots of hazy and gt images in h5 format. I chose 160 of them as training and 40 as val data and tried to train the network. the loss is around 0.005, but when I am taking the 10th epoch and test an image with it, I get yellow images!! do you have any idea what is the reason??
> 
> thanks Mojgan

I also encountered this issue. The images from my tests turned out yellowish. Have you managed to solve this problem?
